### ISSUE TITLE
上传失败了：Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by casatwy** [coolswitch/tiptap-extension-image-upload#4]
我上传文件的时候失败了，走到了下面这一句：
<img width="1006" alt="截屏2024-05-27 11 26 26" src="https://github.com/coolswitch/tiptap-extension-image-upload/assets/1005781/51c5c60f-f429-4033-8514-52c56d603c56">

然后我自己加了个console.log打印了一下：
<img width="557" alt="截屏2024-05-27 11 27 07" src="https://github.com/coolswitch/tiptap-extension-image-upload/assets/1005781/68b41612-f4e2-454c-89dc-99cab7289096">

结果里确实是没有image：
<img width="842" alt="截屏2024-05-27 11 26 34" src="https://github.com/coolswitch/tiptap-extension-image-upload/assets/1005781/42f9ae0b-79ad-4bc1-ab69-e1d18246babc">

我应该怎么办咧？

**Comment by coolswitch** [comment]
你的tiptap或prosemirror没有引用image的schema

https://tiptap.dev/docs/editor/api/nodes/image
https://prosemirror.net/docs/ref/#schema-basic.nodes.image
